job('First-Maven-Project-Via-DSL') {
  description("First Maven job generated by the DSL on ${new Date()}, the porject is a small Maven project hosted on github")
  scm {
       git("git@github.com:harikrishna83/maven-samples.git", 'master')
  }
  triggers {
       scm('* * * * *')
  }
  steps {
       maven('clean package', 'single-module/pom.xml')
  }
  publishers {
         //archive the war file generated
         archiveArtifacts '**/*.jar'
  }
}
